targets:
  $default:
    builders:
      code_gen_exp|locating_builder:
        enabled: true
      code_gen_exp|node_aggregating_builder:
        enabled: true

builders:
  locating_builder:
    import: 'package:code_gen_exp/builder.dart'
    builder_factories: ['locatingBuilder']
    build_extensions: { '.dart': ['.tlwr'] }
    auto_apply: dependents
    build_to: cache

  node_aggregating_builder:
    import: 'package:code_gen_exp/builder.dart'
    builder_factories: ['nodeAggregatingBuilder']
    build_extensions: { r'$lib$': ['tlwr.txt'] }
    auto_apply: dependents
    build_to: source