targets:
  $default:
    builders:
      code_gen_exp|page_builder:
        enabled: true

builders:
  page_builder:
    import: "package:code_gen_exp/builder.dart"
    builder_factories: ["pageBuilder"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: source
